server:
  port: 8094

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://servicio-eureka-server:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://postgres-gestor:5432/sgv_gestor
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

vectorial-layer:
  status:
    withoutPresenting: SIN_PRESENTAR
    ommited: OMITIDA
    inRevision: EN_REVISION
    approved: APROBADO
    observed: OBSERVADO
    pending: PENDIENTE
    toModify: A_MODIFICAR

service-client:
  email:
    baseUri: http://localhost:8091
    emailUri: /api/emails/send