server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/gestor
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    # hikari:
    #   maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

vectorial-layer:
  states:
    withoutPresenting: SIN_PRESENTAR
    ommited: OMMITED
    inRevision: EN_REVISION
    approved: APROBADO
    observed: OBSERVADO
