server.port=${PORT:0}
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.client.service-url.defaultZone=http://servicio-eureka-server:8761/eureka

spring.datasource.url=jdbc:postgresql://postgres:5432/sgv
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.hikari.maximum-pool-size=5
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Enable Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
